### ISSUE TITLE
Instructions on usage?

### ISSUE THREAD

**Issue by dalanmiller** [cloudflare/pngcrush#1]
Hi there! 

I'm trying to find a tool to compress some PNG files and come across this. How would I go about making and using this?

**Comment by vkrasnov** [comment]
We are not the creators of pngcrush. The original pngcrush can be found here http://pmt.sourceforge.net/pngcrush/index.html. Ours simply uses faster zlib implementation.
You can use this command line with pngcrush:
pngcrush -brute -rem alla -rem text InputFile.png OutputFile.png

**Comment by dalanmiller** [comment]
Thanks for the response @vkrasnov! 

(I forgot to close this!)
